# Inorder to make the image clone isaac_ros_common and run_dev.sh
# https://nvidia-isaac-ros.github.io/repositories_and_packages/isaac_ros_apriltag/isaac_ros_apriltag/index.html
FROM nvcr.io/nvidia/isaac/ros:aarch64-ros2_humble_fd3cefe09df8d19bf6cc82b0d57de78d

RUN sudo apt-get update && sudo apt-get install -y ros-humble-isaac-ros-apriltag


