#!/bin/bash

GITHUB_REGISTRY="ghcr.io/gold-rush-robotics"
VERSION="5.1-36.4.7"
IMAGE_NAME="jetson-zed:$VERSION"

docker build -t $GITHUB_REGISTRY/$IMAGE_NAME --cache-from $GITHUB_REGISTRY/$IMAGE_NAME . 

echo "Build finished"

echo "Would you like to run the image in interactive mode? (y/n)"
read INTERACTIVE

if [ "$INTERACTIVE" = "y" ]; then
    docker run -it -v /dev:/dev --privileged  $GITHUB_REGISTRY/$IMAGE_NAME
fi

echo "Would you like to push the image to the registry? (y/n)"
read PUSH

if [ "$PUSH" = "y" ]; then
    docker push $GITHUB_REGISTRY/$IMAGE_NAME
fi
