#!/bin/bash

GITHUB_REGISTRY="ghcr.io/gold-rush-robotics"
VERSION="1"
IMAGE_NAME="circuit-python-ros:$VERSION"

docker buildx build --platform=linux/amd64,linux/arm64 --push -t $GITHUB_REGISTRY/$IMAGE_NAME .

echo "Build finished"
