#!/bin/bash

GITHUB_REGISTRY="ghcr.io/gold-rush-robotics"
VERSION="1"
IMAGE_NAME="newton:$VERSION"

docker buildx build --platform linux/amd64 -t $GITHUB_REGISTRY/$IMAGE_NAME --cache-from $GITHUB_REGISTRY/$IMAGE_NAME --load . 

echo "Build finished"

echo "Would you like to run the image in interactive mode? (y/n)"
read INTERACTIVE

if [ "$INTERACTIVE" = "y" ]; then
    docker run --rm -it --entrypoint /bin/bash $GITHUB_REGISTRY/$IMAGE_NAME
fi

echo "Would you like to push the image to the registry? (y/n)"
read PUSH

if [ "$PUSH" = "y" ]; then
    docker push $GITHUB_REGISTRY/$IMAGE_NAME
fi