#!/bin/bash

GITHUB_REGISTRY="ghcr.io/gold-rush-robotics"
VERSION="latest"
IMAGE_NAME="dev_env:$VERSION"

docker build -t $GITHUB_REGISTRY/$IMAGE_NAME --cache-from $GITHUB_REGISTRY/$IMAGE_NAME . 

echo "Build finished"

echo "Would you like to run the image in interactive mode? (y/n)"
read INTERACTIVE

if [ "$INTERACTIVE" = "y" ]; then
    docker run --rm -it -e ACCEPT_EULA=y --entrypoint /bin/bash $GITHUB_REGISTRY/$IMAGE_NAME
fi

echo "Would you like to push the image to the registry? (y/n)"
read PUSH

if [ "$PUSH" = "y" ]; then
    docker push $GITHUB_REGISTRY/$IMAGE_NAME
fi