#!/bin/bash

GITHUB_REGISTRY="ghcr.io/gold-rush-robotics"
VERSION="4"
IMAGE_NAME="dev_env:$VERSION"

docker buildx build --platform=linux/amd64,linux/arm64 --push -t $GITHUB_REGISTRY/$IMAGE_NAME .

echo "Build finished"
